name: Security Analysis
env:
  DOTNET_VERSION: '8.x'
on: push
jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Snyk
        run: npm install -g snyk

      - name: Ejecutar análisis de Snyk
        run: snyk test --json-file-output=snyk-report.json

      - name: Convertir Snyk a HTML
        run: npx snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Mover el reporte de Snyk a la carpeta 'public/snyk'
        run: |
          mkdir -p public/snyk
          mv snyk-report.html public/snyk/

  semgrep-analysis:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    needs: snyk-analysis
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar prospector-html
        run: python -m pip install prospector2html

      - name: Ejecutar Semgrep scan
        run: semgrep scan --config="p/default" --json --output semgrep.json --metrics=off

      - name: Convertir a HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      - name: Mover el reporte de Semgrep a la carpeta 'public/semgrep'
        run: |
          mkdir -p public/semgrep
          mv semgrep-report.html public/semgrep/

  deploy:
    runs-on: ubuntu-latest
    needs: [snyk-analysis, semgrep-analysis]
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.G_TOKEN }}
          publish_dir: public
