name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install SonarQube Scanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Start SonarQube analysis
      run: dotnet-sonarscanner begin /k:"testproyectopdf_proyectopdftest" /o:"proyectopdftest" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build the project
      run: dotnet build PROYECTOPDFFINAL/ProyectoPDF.sln

    - name: Run tests
      run: dotnet test PROYECTOPDFFINAL/ProyectoPDF.sln --no-build

    - name: Complete SonarQube analysis
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"