name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  sonarcloud:
    name: SonarQube Scan
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Restore NuGet packages
        run: dotnet restore PROYECTOPDFFINAL.sln

      - name: Build the solution
        run: dotnet build PROYECTOPDFFINAL.sln --no-restore

      - name: Run tests and collect coverage
        run: |
          dotnet test NegocioPDF.Tests/NegocioPDF.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
        continue-on-error: true

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"PROYECTOPDF" /o:"proyectopdftest" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          dotnet build PROYECTOPDFFINAL.sln
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
